main:
  web_trigger_udpate: &web_trigger_update
    - name: Update fdroid branch
      runner:
        cpus: 2
      docker:
        image: mobiledevops/android-sdk-image:34.0.1
      imports: "https://cnb.cool/aalivexy/fdroid-env/-/blob/main/env.yml"
      stages:
        - name: Install astral-sh/uv
          script: curl -LsSf https://astral.sh/uv/install.sh | sh
        - name: Install dependencies
          script: uv sync
        - name: Check for updates
          script: uv run main.py
        - name: Update fdroid branch
          if: '[ ! -d "fdroid" ]'
          script: |
            cd fdroid
            git init --initial-branch=main
            REMOTE_URL="$(git -C ../ config --get remote.origin.url)"
            if [ -n "$REMOTE_URL" ]; then
                git remote remove origin 2>/dev/null || true
                git remote add origin "$REMOTE_URL"
            fi
            git add .
            git commit -m "Update fdroid branch"
            git push --force origin main:fdroid

  "crontab: 0 4,16 * * *":
    - <<: *web_trigger_update
